# This is a basic workflow to help you get started with Actions

name: pdf

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create-pdf:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
  
      - name: Markdown to PDF and HTML
        # You may pin to the exact commit or the version.
        # uses: BaileyJM02/markdown-to-pdf@efc04d3f22971dfbb6b571333469119cfb6a926c
        uses: BaileyJM02/markdown-to-pdf@v1
        with:
          # (Path) The location of the folder containing your .md or .markdown files
          input_dir: resume/

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: resume/README.pdf
          asset_name: Resume-MateusWolfartBechert.pdf
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my resume's PDF version"
